#include "common.h"

const std::vector<TargetTagMetadata> METADATA_REGISTRY = {
    {"Title", "TITLE", "TIT2"},
    {"Artist", "ARTIST", "TPE1"},
    {"Album", "ALBUM", "TALB"},
    {"Album_Artist", "ALBUMARTIST", "TPE2"},
    {"Composer", "COMPOSER", "TCOM"},
    {"Lyricist", "LYRICIST", "TEXT"},
    {"Genre", "GENRE", "TCON"},
    {"Comment", "COMMENT", "COMM"},
    {"Lyrics", "LYRICS", "USLT"},
    {"Compilation", "COMPILATION", "TCMP"},
    {"Description", "DESCRIPTION", "TIT3"},
    {"Front_Cover", "METADATA_BLOCK_PICTURE", "APIC"}, 
    {"Back_Cover", "METADATA_BLOCK_PICTURE", "APIC"}, 
    {"File_Icon", "METADATA_BLOCK_PICTURE", "APIC"}, 
    {"During_Performance", "METADATA_BLOCK_PICTURE", "APIC"}, 
    {"Date", "DATE", "TDRC"}, 
    {"Track_Number", "TRACKNUMBER", "TRCK"}, 
    {"Disc_Number", "DISCNUMBER", "TPOS"}, 
    {"Duration", "DURATION", "TLEN"}, 
    {"Bit_Rate", "BITRATE", "TXXXX:BITRATE"}, 
    {"Bit_Rate_Mode", "BITRATEMODE", "TXXXX:BITRATEMODE"},
    {"Sample_Rate", "SAMPLERATE", "TXXXX:SAMPLERATE"},
    {"Bit_Depth", "BITDEPTH", "TXXXX:BITDEPTH"},
    {"Channels", "CHANNELS", "TXXXX:CHANNELS"},
    {"Channel_Layout", "CHANNELLAYOUT", "TXXXX:CHANNELLAYOUT"},
    {"Audio_Codec", "AUDIOCODEC", "TXXXX:AUDIOCODEC"},
    {"Profile", "PROFILE", "TXXXX:PROFILE"},
    {"Container_Format", "CONTAINERFORMAT", "TXXXX:CONTAINERFORMAT"},
    {"File_Size", "FILESIZE", "TXXXX:FILESIZE"},
    {"Compression_Ratio", "COMPRESSIONRATIO", "TXXXX:COMPRESSIONRATIO"},
    {"Stream_Size", "STREAMSIZE", "TXXXX:STREAMSIZE"},
    {"Audio_MD5", "AUDIOMD5", "TXXXX:AUDIOMD5"}
};
